### ISSUE TITLE
GPG Time Warning Issue

### ISSUE THREAD

**Issue by mmmmie** [HelloThisIsFlo/Deckpad#10]
When I tried to run the third step which is running ./initialize_after_os_update.sh. I get a load of gpg: WARNING: running with faked system time: 2023-01-01 00:00:00. And the process will be running forever in a loop. I've tried 'sudo timedatectl set-ntp true' 
and 'gpg --refresh-keys' but didn't work. Here's a screenshot of it.
![Screenshot_20231010_020849 (1)](https://github.com/HelloThisIsFlo/Deckpad/assets/37318622/e299a7af-3a9c-4d2f-84f2-f055043fcd40)

**Comment by HelloThisIsFlo** [comment]
Hi @mmmmie,

This step produces a lot of warnings, but usually still works. I think the warnings are related to specific keys failing, but the ones that matter are successfully updated. But that's just an educated guess. So, in theory it should be fine ...

... however, since Steam OS 3.5, I can't get Deckpad to install anymore. I've documented this in #12 

Please follow #12 if you want to be informed on the developments on that side, I'm closing this issue for now.

Thanks for reporting!
