### ISSUE TITLE
Deckpad still tells me to run ./initialize_after_os_update.sh after doing it

### ISSUE THREAD

**Issue by xJusteen47** [HelloThisIsFlo/Deckpad#13]
When i run the shell command, it gives me a bunch of errors downloading files from various sources and then after it ends it tells me to press enter to continue. I do that but nothing happens.

When i open deckpad it tells me still that i have to run it first.

so I can't use deckpad

**Comment by HelloThisIsFlo** [comment]
Did you use the lastest version?

I fixed a similar issue a few weeks ago, it started appearing after Steam OS 3.5 was released

If you are using the lastest version, could you share the errors you're getting?

**Comment by HelloThisIsFlo** [comment]
Also what could happen is that the `sudo` session times out after refreshing the keys, then it asks for the password again. If not provided, it will timeout.

In that scenario, relaunching the script would end up in the same situation. Since it's quite annoying to keep an eye on the script to see if it would ask for a password a second time, I've added an option to skip the refresh keys step. 

If you've run the script once and the refresh keys step worked (the `gpg errors` are expected), then you can just run

```shell
./initialize_after_os_update.sh --skip-refresh-keys
```

This will be much quicker, hopefully that works for you. If other people have a similar issue, I may consider streamlining the installation process

**Comment by HelloThisIsFlo** [comment]
Oh no! My bad !!

**I found the problem, it was 100% on my end.** Thank you for reporting it!

I'll push a fix in a minute

---
Explanation:
To solve the `sudo` timeout mentioned above I added a prompt that says:
```
------------------------------
| Press Enter to continue... |
------------------------------
```
But I forgot to remove a line that was there while I was testing things `exit 0`, that basically ends the script and never installs the required dependencies. So, with or without the option mentioned above, nothing would happen after you press `Enter`.

**Comment by HelloThisIsFlo** [comment]
Done. 
This should fix the issue: https://github.com/HelloThisIsFlo/Deckpad/commit/fba422fd8c51283ef724246fdc063979f4f3ccda

Just pull the project to get this change and run
```shell
./initialize_after_os_update.sh --skip-refresh-keys
```
The option `--skip-refresh-keys` skips the super long step that was already done the first time you ran the script.

I'm closing the issue for now, but if it's still not working, for some reason, feel free to re-open. Thanks again for letting me know I haven't used Deckpad in a while myself, so it could have taken me a few weeks, or months, to notice that.
