### ISSUE TITLE
touchscreen is unresponsive 

### ISSUE THREAD

**Issue by PureRussianVodka** [HelloThisIsFlo/Deckpad#7]
on the latest version of the steam OS the UI seams to be stuck to the left side of the screen and is unresponsive to touch. can we simply have it so it responds to touch anywere on the device?

**Comment by HelloThisIsFlo** [comment]
I'll take a look at it before the end of the month, in the meantime, if you want to enlarge the touch zone, you can change the value of these 4 variables: https://github.com/HelloThisIsFlo/Deckpad/blob/83cdb7b67f8b331c605c96d0fc9baf7baec6a74e/functions.sh#L36-L39

**Comment by admiral0912** [comment]
So, the current pull has those variables (just checked my own functions.sh cloned from a few hours ago), and I also run into the issue where no matter where on the display I touch, Deckpad will not close and the SteamOS keyboard pops up. Opening a new Konsole window and using the commands from the readme doesn't work, and only rebooting the device seems to have any effect.

I wonder, would it be possible to also include a command prompt way of exiting for when the touchscreen is unresponsive/SteamOS makes a change interfering with one input method? I don't think the current window that opens is capable of being used for any commands, just for the interface which does make sense. But given that the issue has seemingly been occurring for at least some users, I can't help but be curious if there's another way to have an exit and cleanup function. I'm not in any way shape or form an authority or knowledgeable in this area, so it may very well not be possible.

**Comment by HelloThisIsFlo** [comment]
Hi @PureRussianVodka 

I figured out what the problem was in your case. After updating the OS it's important to always run
```
 ~/Deckpad/install_pacman_packages.sh
```

I agree however that it was not very clear in the readme, I added a warning. 

On top of that, initial prototypes of Deckpad used to work without the `figlet` dependency, but the final version does require it. So, when it wouldn't find it, instead of crashing or showing a warning it would look like it works, sort of, but all the test would be squished to the left, as you described. I changed this behaviour, it will now should you a warning with instructions if you try to run Deckpad after a Steam OS update without running ` ~/Deckpad/install_pacman_packages.sh`. 

It's now live:  https://github.com/HelloThisIsFlo/Deckpad/commit/fab1a8ba482559ec0242a9a6daeceef6400ec4ff
